app:
  log:
  - level: verbose
    file: stderr

generators:
  gotemplate:foo:
    useBuiltIn: telegraph

storage:
  router:foo:
    specs:
    - mimeMatch: (image|video)
      maxSize: 5242880 # 5MB
      telegraph: {}
    # - mimeMatch: .*
    #   s3: {}

publishers:
  telegraph:foo: {}

bots:
  telegram:foo:
    enabled: true

    appID@env: $TG_APP_ID
    appHash@env: $TG_APP_HASH
    appPubKey@env: $TG_APP_PUBKEY

    botToken@env: $TG_BOT_TOKEN

    workflows:
    - generator: gotemplate:foo
      storage: router:foo
      publisher: telegraph:foo

      adminOnly: true
      downloadMedia: true
      cmdMapping:
        /new:
          as: /discuss
          description: start a new discussion around some topic
        /resume:
          as: /continue
          description: continue previous discussion
