include:
# add renderer `presets`
- text@http?str: https://raw.githubusercontent.com/arhat-dev/dukkha-presets/dev/setup-dev.yml
- path: cicd

renderers:
- http:
    cache:
      enabled: true
      timeout: 5h
