name: CI

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reason:
        description: reason to run this workflow
        required: false
        default: test

  pull_request:
    paths-ignore:
    - docs/**
    - cicd/deploy/charts/**
    - README.md
    branches:
    - master
    - "!deps/**"

  push:
    paths-ignore:
    - docs/**
    - cicd/deploy/charts/**
    - README.md
    branches:
    - master
    - "!deps/**"
    tags:
    - v*

jobs:
  stylecheck:
    uses: arhat-dev/dukkha-presets/.github/workflows/stylecheck.yml@master

  test:
    uses: arhat-dev/dukkha-presets/.github/workflows/test.yml@master
    with:
      matrix: |-
        {
          "os": [
            "macos-latest",
            "windows-latest",
            "ubuntu-latest"
          ],
          "go": [
            "1.18.x"
          ]
        }
    secrets:
      sonarqube-server-url: ${{ secrets.SONAR_HOST_URL }}
      sonarqube-token: ${{ secrets.SONAR_TOKEN }}

  artifacts:
    needs:
    - stylecheck
    - test
    uses: arhat-dev/dukkha-presets/.github/workflows/artifacts.yml@master
    with:
      release: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-private-key-password: ${{ secrets.COSIGN_PRIVATE_KEY_PASSWORD }}

  images:
    needs:
    - stylecheck
    - test
    uses: arhat-dev/dukkha-presets/.github/workflows/images.yml@master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-private-key-password: ${{ secrets.COSIGN_PRIVATE_KEY_PASSWORD }}
